### ISSUE TITLE
[REQUEST] 1.12.2 SUPPORT

### ISSUE THREAD

**Issue by TeQTabanca** [hyperdefined/ToolStats#12]
**I've tried a lot of plugins of this type, they all give errors and are no longer updated. Any chance of adding 1.12.2 support to this plugin?**

**Comment by hyperdefined** [comment]
This plugin uses [PersistentData](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/persistence/PersistentDataContainer.html) to save data on the items. This isn't available on 1.12.2, as it was added in 1.14.1. This would require a complete rewrite of how the data is saved, which I am not really interested in as this plugin already took me a long time to create.
