### ISSUE TITLE
[v1.4.1] Could not pass LootGenerateEvent

### ISSUE THREAD

**Issue by noiverre** [hyperdefined/ToolStats#14]
**Error log**:
https://paste.gg/p/anonymous/ecae2e15556146eeb15f8b8f27801fa9

**Additional info**:
This server is running Paper version git-Paper-27 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b77fe3a)

**Comment by hyperdefined** [comment]
Thank you for the report. I BELIEVE I know what the issue is, but I'm not available until later my time to work on it. I will when I can!

**Comment by hyperdefined** [comment]
As suspected, I reproduced the problem on my end. I went ahead and fixed this on the new version:

https://github.com/hyperdefined/ToolStats/releases/tag/1.4.2

Again, thank you for reporting this bug! I would have never caught this myself because this is a "rare" occurrence bug.
