### ISSUE TITLE
Combo Issue with EvenMoreFish

### ISSUE THREAD

**Issue by DragaoNimhe** [hyperdefined/ToolStats#18]
Hello! I've added your plugin in combination with the plugin EvenMoreFish, and I've run across an issue that I know a fellow server owner is also having. Unfortunately I won't be able to provide as much information as I usually like to in my reports, as we're under a bit of a crunch right now and I don't have time for extensive testing. Here's what I know:

My fishing rod does not have any issues, and the counter works perfectly with or without "bait" from EMF present.

Another players fishing rod does have issues, and instead of the counter appearing on her rod, it adds a line to the lore with each fish caught, resulting in rods that look like this:
![image](https://user-images.githubusercontent.com/12823393/193752870-bb7db8e8-4f13-45e8-977a-fc85db38abe3.png)

I tested with a rod of my own that had no lore, and the issue was not present.

I had her test with several rods:
- enchanted
- unenchanted
- freshly crafted
- named
- with/without bait

...and it happened to each. If my team can help in any way, or you need my help getting in contact with Oheers (dev of EvenMoreFish) please don't hesitate to ask; I'm happy to assist however I can!

**Comment by ClickErrorxD** [comment]
I can voucher for this issue.
Same lore issue exactly - couldn't reproduce myself, but my player's had gotten the issue themselves.

**Comment by hyperdefined** [comment]
I did a quick test of this myself, and I cannot seem to reproduce it. Whenever she catches a fish, do any errors appear in the console? Do you have a messages set under `messages.fished` in the config? Also, what server software are you using (Spigot, Paper, etc)? Because it looks to me like it's failing to find the message from the config and is just adding a blank message instead.

(If you are using Paper, can you hold the item and type `/paper dumpitem` and copy the contents here?)

**Comment by DragaoNimhe** [comment]
I'll get to this shortly :)

**Comment by hyperdefined** [comment]
I would love to get this fixed for you, since this is a weird specific problem I have never seen before.

**Comment by DragaoNimhe** [comment]
Paper Itemdump:
minecraft:fishing_rod{Damage:0,Enchantments:[{id:"minecraft:luck_of_the_sea",lvl:3s},{id:"minecraft:lure",lvl:3s},{id:"minecraft:mending",lvl:1s},{id:"minecraft:unbreaking",lvl:3s}],PublicBukkitValues:{"toolstats:fish-caught":16},RepairCost:15,display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}']},evenmorefish:{}}

**Comment by DragaoNimhe** [comment]
Vs my own rod which did not have this issue:
minecraft:fishing_rod{Damage:0,Enchantments:[{id:"minecraft:luck_of_the_sea",lvl:3s},{id:"minecraft:lure",lvl:4s},{id:"minecraft:mending",lvl:1s},{id:"minecraft:unbreaking",lvl:3s}],PublicBukkitValues:{"toolstats:fish-caught":79},RepairCost:1,display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Whoa, you found a really"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"special fishing rod!"}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Fish caught: "},{"italic":false,"color":"dark_gray","text":"23"}],"text":""}'],Name:'[{"text":"Dad\'s Best Fisher","italic":false,"color":"light_purple"}]'},evenmorefish:{}}

**Comment by DragaoNimhe** [comment]
Unfortunately I can no longer replicate this issue as the player it was affecting is no longer affected by it. I'll re-comment if we find someone else.

**Comment by DragaoNimhe** [comment]
Also can i just say this bug is WEIRD AS HELL.

**Comment by DragaoNimhe** [comment]
Update: Another one happened. 0 errors in console. Here's the new paper readout
minecraft:fishing_rod{Damage:0,Enchantments:[{id:"minecraft:luck_of_the_sea",lvl:3s},{id:"minecraft:lure",lvl:3s},{id:"minecraft:mending",lvl:1s},{id:"minecraft:unbreaking",lvl:3s}],PublicBukkitValues:{"toolstats:fish-caught":157},RepairCost:7,display:{Lore:['{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}','{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Fish caught: "},{"italic":false,"color":"dark_gray","text":"157"}],"text":""}']},evenmorefish:{}}

**Comment by DragaoNimhe** [comment]
Lucked out and my own girlfriend was hit with the bug.
So far:
- relogging did not fix the bug.
- post-reboot, casting with or without bait and a brand new rod, the bug was no longer present
- post-reboot, casting with or without bait and the previously affected rod, the bug was no longer present

So it seems like whoever is selected to be affected by this bug is chosen upon reboot, then wiped on the next.

**Comment by hyperdefined** [comment]
Sorry for the late replies, been busy with school. From what I can see, EvenMoreFish is trying to change the fishing rod at the same time as ToolStats? Something is just not working together.

At the last itemdump, I can see my plugin attempted to add the lore `"text":"Fish caught: "` but somehow failed to read the current caught count, which is set correctly `PublicBukkitValues:{"toolstats:fish-caught":157}`. 

Again, I will try again to reproduce the bug, since I can't tell what's going on otherwise. Thanks again for the help so far!

**Comment by hyperdefined** [comment]
I possibly have figured out a solution, and I would like for you to test with a debug version. This debug version will output somethings to the console. Please try with a rod until it happens again. When it happens, copy and paste the contents of your console. You want the lines between `Fishing rod currently has lore:` to `Fishing rod lore after counting:` (with the next line). These lines tell me what my plugin is doing, and hopefully can tell what is happening.

I even tried with the broken rod you gave me (using `/paper dumpitem`) and it seems to be fine on my end. I believe I was correct with the problem, both plugins were trying to edit the rod at the same time, and it just  breaks. I changed my plugin to run first (using priorities). So my lore changes run first, then EvenMoreFish.

Once again, thank you so much for giving me a lot of information that I have been using. I'm sorry that I haven't on this sooner, just been busy with school.

Here is the debug plugin. Since GitHub won't let me upload jar files, it's in a zip file instead: [toolstats-1.4.5-FISH-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9718853/toolstats-1.4.5-FISH-DEBUG.zip)

**Comment by DragaoNimhe** [comment]
I'll get to this within the next hour or two. TYSM.

**Comment by hyperdefined** [comment]
I made a mistake with something in the plugin, please use this one instead: 
[toolstats-1.4.5-FISH-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9718941/toolstats-1.4.5-FISH-DEBUG.zip)

**Comment by DragaoNimhe** [comment]
> I made a mistake with something in the plugin, please use this one instead: [toolstats-1.4.5-FISH-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9718941/toolstats-1.4.5-FISH-DEBUG.zip)

Booted with this now.

**Comment by DragaoNimhe** [comment]
Okay can confirm the error is still present with this new jar. Here's a debug readout of an affected user fishing. This is not when the issue first began for this issue, just when they noticed and called my attention to it.

https://pastebin.com/E4DmcP82

**Comment by hyperdefined** [comment]
Yeah that log by itself doesn't really tell me anything, I was hoping to see the log whenever a fishing rod broke (when a blank line gets added to a fresh rod). For now, I can probably do a hacky solution of just checking if the plugin is installed, and removing blank lines.

It's hard for me to test just because I can't seem to reproduce it on my end.

**Comment by DragaoNimhe** [comment]
Yes unfortunately despite me shouting out that I needed logs from when a rod broke, she didn't notice until nearly an hour later (we think). I'll dig through logs and see if I can find the moment it broke; I was afraid of that but also dead busy last night.

**Comment by DragaoNimhe** [comment]
I believe the rod broke somewhere here, but I don't see a clear error associated with the break.

https://pastebin.com/23Pw9ZBd

**Comment by hyperdefined** [comment]
Again, sorry for the delays, I am not loosing hope!

Good and bad news based on that log. Good news, it seems to me that my plugin is not adding the blank lines. I figured it wasn't, but that log does help me a lot.

Those blank lines are actually just empty lines with color formatting. This is how spacing is done. If you look at the itemdump, you can see a bunch of `white` being listed. They are actually just `§f`, which is white. My plugin does not add these lines, EvenMoreFish does (they again use that for spacing for the bait list).

Bad news, I still don't understand *why* they are being added. After some thinking, I figured it was something with event priorities. EvenMoreFish uses the `HIGHEST` priority on the fish event, which means their code will run last. I changed mine to also use `HIGHEST` in the debug version I gave you, so they were both trying to edit a rod at the same time. However, even before this, my events were set to `NORMAL`, which runs before EvenMoreFish. I also started to get some weird errors from EvenMoreFish, something to do with the fishing rod not being there for the event.

I will try and tinker around again with how I set the fishing rod on my end, and hopefully stop this problem.

**Comment by DragaoNimhe** [comment]
I have *heavily* edited EMF's config. I bug the dev often, welcome to the party haha.
What part would you be specifically interested in seeing? I won't subject you to the entirety of my configs... I value you and don't want to kill you with the weight of them.

**Comment by hyperdefined** [comment]
Sorry, I'm not sure what I meant by `locales`, that doesn't even exist.

I am interested in seeing the `format` section under `baits.yml` at the bottom. That section is the lore for the baits, and I want to copy yours directly to test.

**Comment by DragaoNimhe** [comment]
format:
  # How the lore should look ({baits} takes up multiple lines)
  rod-lore:
    - "&f"
    - "&7Bait Slots: &e({current_baits}/{max_baits})"
    - "&f"
    - "{baits}"
    - "&f"

  # The default lore of the bait, changing this will not modify existing baits, but with an /emf admin reload, new baits
  # given out will have this lore. Bait themes can be set as a colour or prefix and be used in this lore.
  bait-lore:
    - "&f"
    - "{lore}"
    - "&f"
    - "&#dadadaDrop onto a fishing rod to apply,"
    - "&#dadadaor hold &nSHIFT&#dadada to apply all."
    - "&f"
  # How the baits should look in each line of the {baits} variable above ^. {baits} respects the display name setting,
  # the &e is there for baits without a display name set.
  baits: "&6► {amount} {bait}"

  # These are listed in the {boosts} variable above in bait-lore
  # boost-rarity/rarities: shown when the bait only impacts 1 rarity or when it impacts multiple rarities.
  # boost-fish: shown when the bait impacts some fish individually.
  boosts-rarity: "{bait_theme}► &f1 {bait_theme}Rarity"
  boosts-rarities: "{bait_theme}► &f{amount} {bait_theme}Rarities"
  boosts-fish: "{bait_theme}► &f{amount} {bait_theme}Fish"

  # This is added to the lore in place of a bait if show-unused-slots is enabled in the general section.
  unused-slot: "&7► ? &oAvailable Slot"

config-version: 1

**Comment by DragaoNimhe** [comment]
Edited out the #'s as they were causing huge text <<;

Also worth mentioning I haven't had this issue in almost a week now and I haven't changed anything so as far as i can tell this bug is actually magic...?

**Comment by DragaoNimhe** [comment]
AS I was typing that comment it happened again so I'm adding "and is sentient/hates us" to that.

**Comment by DragaoNimhe** [comment]
Update: One of my admins has added a /fixlore command to negate this issue in the meantime <3

**Comment by DragaoNimhe** [comment]
Another update:
It happens to me WAY more often with this specific fishing rod:

give %player-name% fishing_rod{AttributeModifiers:[{AttributeName:"generic.max_health",Amount:4.0,Slot:mainhand,Name:"generic.max_health",UUID:[I;-122922,34537,20520,-69074]},{AttributeName:"generic.attack_damage",Amount:10,Slot:mainhand,Name:"generic.attack_damage",UUID:[I;-122922,34637,20520,-69274]}],display:{Name:'[{"text":"Soul-Stealer","italic":false,"bold":true,"color":"gold"}]',Lore:['[{"text":"Legend says that this rod","italic":false,"color":"white"}]','[{"text":"can hook the very soul of","italic":false,"color":"white"}]','[{"text":"the fish, and pull it right","italic":false,"color":"white"}]','[{"text":"out of its body!","italic":false,"color":"white"},{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"","italic":false,"color":"dark_purple"}]','[{"text":"This item was only obtainable","italic":false,"color":"gray"}]','[{"text":"during ","italic":false,"color":"gray"},{"text":"Halloween 2022 Event Week","bold":true},{"text":"!","bold":false}]']},Enchantments:[{id:vanishing_curse,lvl:1},{id:fire_aspect,lvl:2},{id:knockback,lvl:2},{id:looting,lvl:3},{id:lure,lvl:4},{id:mending,lvl:1},{id:smite,lvl:6},{id:unbreaking,lvl:3}]} 1

**Comment by hyperdefined** [comment]
I believe I have *finally* been able to reproduce the problem on my end. I used the fishing rod you gave me, and using up baits seems to cause the empty lines to be added. I removed ToolStats and tried it again, and it did not happened. From what I can tell, it's removing my lore and replacing it with an empty space when a bait gets removed. Our plugins are just battling the lore of the rod.

I will go ahead and try to work around it, knowing I can actually see the bug on my end. Sorry for taking so long, it's hard to fix something when I can't reproduce it. But alas, I can start to work on fixing it!

**Comment by hyperdefined** [comment]
I'll leave you a test plugin once again. This fix was super easy and kinda obvious, but again I couldn't test it earlier since I didn't get the bug myself.

Try this version with that same rod, add some baits and report back!
[toolstats-1.5.2-debug.zip](https://github.com/hyperdefined/ToolStats/files/9944689/toolstats-1.5.2-debug.zip)

**Comment by DragaoNimhe** [comment]
Apologies, I had a rough week (kitten REFUSES to let me sleep, nothing bad lmao) so i'm just now getting to this. Will report back ASAP (read; probably tomorrow after I get some sleep... I hope).

**Comment by hyperdefined** [comment]
No worries, I've myself had a rough week with a lot of stuff going on. I hope that the test plugin fixes the problem for you, since this bug is reallllyyyy annoying. I didn't only fix the fishing rod issue, I hopefully improved compatibility for all tracking with all plugins.

**Comment by DragaoNimhe** [comment]
Yeah this week has been hell. We had a ton of bugs crop up out of the blue and had to do some pest control. Finally calming down.

**Comment by DragaoNimhe** [comment]
I come bearing bad news.
- It took me so long to test because insurance decided I don't need coverage on my anxiety meds anymore, and withdrawal = my brain was removed from my damn skull for a week. Finally on the way out of that hell.

- So we tested it and... 
https://cdn.discordapp.com/attachments/1040056439764439132/1045884549659365396/image.png

Issue still presents regardless of rod used, lore or no lore.

**Comment by DragaoNimhe** [comment]
Btw totally ready to stop caring whenever you are, and if you would like me to share our /fixlore command structure I'm happy to :'D

**Comment by hyperdefined** [comment]
That's truly unfortunate. I really was hoping that would solve the issue, as it seemed to solve it for me. I'm really sorry I couldn't fix this for you. It has to be some other 3rd thing I am missing or not thinking of.

I am curious to see what that command is.
