### ISSUE TITLE
Problem with the value {blocks}

### ISSUE THREAD

**Issue by WaxenSs** [hyperdefined/ToolStats#19]
As soon as a pickaxe has mined more than 1,000 blocks, the value displays a special character:

<img width="116" alt="CleanShot 2022-10-09 at 22 35 55@2x" src="https://user-images.githubusercontent.com/37812331/194778338-bece1244-ebd1-4ddb-ae91-56ba1cb382c2.png">

**Comment by hyperdefined** [comment]
If you're running Paper, can you hold the item and type `/paper dumpitem` for me? If not, don't worry!

Do you have a different language set? Have you modified the config? Do you have a custom resource pack?

**Comment by WaxenSs** [comment]
No problem ! Voilà le résultat de `/paper dumpitem`
Here is the result:
![CleanShot 2022-10-10 at 14 44 09](https://user-images.githubusercontent.com/37812331/194869171-8c9d7933-2e6e-40d9-96a2-88f8c1783451.png)

I actually have a texture pack, but even by disabling it, I have exactly the same problem.
My game is in English (US).

I wonder if the problem can come from Fabric. I'm going to test it right away! 😄

**Comment by WaxenSs** [comment]
Vanilla test: I always have the same problem

**Comment by hyperdefined** [comment]
Hmm, I have also tried to change to different languages, that symbol is very strange...

I can give you a test version that formats numbers with commas differently, if you would wish to test it?

**Comment by WaxenSs** [comment]
Yes, absolutely! I can test in a backup of my own server to see if the problem persists

**Comment by hyperdefined** [comment]
Thank you! I only ask this since I can't seem to get that symbol to show up on my end, might be some weird language thing on whatever host you are using. The way I am formatting the numbers can be simplified regardless.

Here is the test version (ignore any warnings, you should be able to just drop it in your backup server). I can't attach the jar directly so it's in a zip file.

[toolstats-1.5-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9749701/toolstats-1.5-DEBUG.zip)

It should correct itself on the broken item once you mine something.

**Comment by WaxenSs** [comment]
Hey !

I tested your plugin in DEBUG version on my test server, the problem is still present, here is what I tested:
- Broken a block: The special character always appears
- /toolstats reload confirm: The special character always appears
- /toolstats reload confirm and then break a block: The special character always appears
- Disable the plugins Vault, ProtocolLib et PlaceholderAPI-2.11.2. /toolstats reload confirm and then break a block: The special character always appears

This special character is cursed 🤔

**Comment by hyperdefined** [comment]
Thanks for the test! I really appreciate it. That is very strange, I'm not sure what exactly is putting that symbol there. It's not a client issue (like I first thought) since `/paper dumpitem` confirms the symbol is actually there.

Where is your server hosted? Maybe the system has sometime of language set? I will do some testing on my end, since I believe I can try some things out.

**Comment by WaxenSs** [comment]
No worries with pleasure!

I am currently hosting my server on Linux (Debian), my test server is launched directly from a device on macOS.
Thank you for your attempts, I hope we will find a solution!

**Comment by hyperdefined** [comment]
So I tried to set my server to use French as the locale, and I can't seem to reproduce the problem. However, I can give you another test to try?

There will be some debugging in your console. Please send `[ToolStats] Locale:` (this will tell me your machines locale).
Once you break a block, please also copy the messages that the plugin outputs and send them over.
[toolstats-1.5-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9767228/toolstats-1.5-DEBUG.zip)

**Comment by WaxenSs** [comment]
Here are the results:
`[ToolStats] Locale: fr_FR`
`[ToolStats] Config line: §7Blocs minés: §8{blocks} | [10:59:52 INFO]: [ToolStats] Line for lore: §7Blocs minés: §81 099`

From what I see in the logs, there is no special character. I thought the problem could come from my `config.yml` or another plugin, so I did new tests:

- Remove my `config.yml` of the plugin, restart the server and `/toolstats reload confirm` and then break a block: The special character always appears
- Remove my `config.yml` of the plugin, restart the server and `/toolstats reload confirm` and then break a block with a new pickaxe up to +1000: The special character always appears
- Launch a new server (with my test map) with only the plugin `toolstats-1.5-DEBUG`: The special character always appears
- Launch a new server (with a brand new map) with only the plugin `toolstats-1.5-DEBUG`: The special character always appears
Console: `[ToolStats] Config line: §7Blocks mined: §8{blocks} | [ToolStats] Line for lore: §7Blocks mined: §81 071`

<img width="213" alt="CleanShot 2022-10-13 at 11 41 55@2x" src="https://user-images.githubusercontent.com/37812331/195562697-8750653e-64ee-4f82-9510-41d9113815e7.png">

My game server and my test server work with Paper `1.19.2-176`

**Comment by hyperdefined** [comment]
Thank you once again for testing! That symbol is actually there technically in `[ToolStats] Line for lore: §7Blocs minés: §81 099` (the symbol is the "space").

So apparently, that's what symbol Java uses for "spaces" for French. I had no idea that thousand separators in French were spaces! Not sure why Java uses a dumb symbol, but I can hardcode that to be replaced with spaces instead that don't break in Minecraft.

I will ask you once again to test this one more time, as I believe I have solved the problem now knowing how to fix it!
[toolstats-1.5-DEBUG.zip](https://github.com/hyperdefined/ToolStats/files/9778477/toolstats-1.5-DEBUG.zip)

**Comment by DuckyDou** [comment]
I have the same issue (french server too)

**Comment by hyperdefined** [comment]
> I have the same issue (french server too)

If you could too, can you test the plugin I linked in my previous response? It should fix the problem and I need someone to test it.

**Comment by WaxenSs** [comment]
Problem solved (put in my test server with all other plugins and my test map) ! 🤩
I'm waiting for you to release the stable version to put it in my game server !

<img width="200" alt="CleanShot 2022-10-13 at 22 50 10@2x" src="https://user-images.githubusercontent.com/37812331/195707787-671359ad-59da-4d68-bd26-821e808e274b.png">

**Comment by hyperdefined** [comment]
Awesome! Sounds great. I can release the next update pretty soon :)
