### ISSUE TITLE
EntityDamageByBlockEvent Console errors

### ISSUE THREAD

**Issue by DormCraft** [hyperdefined/ToolStats#2]
Plugin version: 1.2
Server version: Paper 1.18.1-186

`05.02 00:11:18 [Server] ERROR Could not pass event EntityDamageByBlockEvent to ToolStats v1.2
05.02 00:11:18 [Server] INFO java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R1.entity.CraftItem cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_18_R1.entity.CraftItem and org.bukkit.entity.LivingEntity are in unnamed module of loader java.net.URLClassLoader @7aec35a)
05.02 00:11:18 [Server] INFO at lol.hyper.toolstats.events.EntityDamage.onDamage(EntityDamage.java:143) ~[toolstats-1.2.jar:?]
05.02 00:11:18 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
05.02 00:11:18 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
05.02 00:11:19 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
05.02 00:11:19 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
05.02 00:11:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1017) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1194) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1184) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1180) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.world.entity.item.ItemEntity.hurt(ItemEntity.java:326) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.world.entity.Entity.lavaHurt(Entity.java:838) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:769) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:710) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.world.entity.item.ItemEntity.tick(ItemEntity.java:105) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
05.02 00:11:19 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-177]
05.02 00:11:19 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]`

**Comment by DormCraft** [comment]
These are filling console, but don't have any effect in-game. Made sure to update to latest paper 186 since, but they are still occurring. My config.yml is at [https://pastebin.com/p5XD0guU](https://pastebin.com/p5XD0guU)

**Comment by hyperdefined** [comment]
This should be an easy fix (problem with the plugin itself). I'll take a look later today and fix it. Look out for a new release soon.

**Comment by hyperdefined** [comment]
I have released a new version that fixes this issue. Please make sure to update!

https://github.com/hyperdefined/ToolStats/releases/tag/1.2.1
