### ISSUE TITLE
Dropped-by tag on crafted items after being held by a mob

### ISSUE THREAD

**Issue by DormCraft** [hyperdefined/ToolStats#22]
Plugin ver 1.5
Game ver 1.19.2 PurPur

![image](https://user-images.githubusercontent.com/72905364/197655255-cd78f2f2-0aab-4179-84c6-94b24d4b7c66.png)

Unsure if this is intentional, but crafted items can have both a crafted-by & dropped-by tag simultaneously. If a player loses their item to a mob and then recovers it by killing the mob, the dropped-by tag is added. This is a minor gripe, but I'd love a config toggle to make these mutually exclusive, so that I don't have to disable dropped-by tags.

Thanks!

**Comment by hyperdefined** [comment]
That is unintentional. I forgot about mobs picking items back up and such. I can make them mutually exclusive! I won't add a config option for this, as the tags are to describe where the items are from. Having 2 tags like that is weird.

**Comment by hyperdefined** [comment]
I'll release the new version for this fix shortly. Once you install the new version, you can use `/toolstats reset` to fix the item. The player who created the item must run the command (if you wish to fix it).

**Comment by DormCraft** [comment]
Much appreciated!
