### ISSUE TITLE
Elytra tag is not always added because of return in loop

### ISSUE THREAD

**Issue by kixmc** [hyperdefined/ToolStats#33]
These returns should be changed to continue so all entities are looped
https://github.com/hyperdefined/ToolStats/blob/master/src/main/java/lol/hyper/toolstats/events/ChunkPopulate.java#LL59C21-L59C21
https://github.com/hyperdefined/ToolStats/blob/master/src/main/java/lol/hyper/toolstats/events/ChunkPopulate.java#LL67C26-L67C26

**Comment by hyperdefined** [comment]
woops, that's a big mistake with this. I'll fix it shortly.
