### ISSUE TITLE
Suggestion: Configurable Empty Line

### ISSUE THREAD

**Issue by knniDE** [hyperdefined/ToolStats#37]
Hey, I would be delighted if a blank line or dashes could be added as a separator in ToolStats.
I have several plugins that add enchantments or other buffs and the ToolStats section at the end looks a bit cramped with all together.
For this reason, I would really appreciate such a small feature! Thank you very much if it can be made possible <3

**Comment by hyperdefined** [comment]
I'll look into this, I rather have it be a single option (maybe like `add-empty-lines`). This would add blank lines around the lore before and after.

**Comment by hyperdefined** [comment]
I might not add this feature. Looking into it, the lore system is pretty black and white. I would have to rewrite most of the lore system for this to function correctly. It would also be a pain trying not to mess other lore on items.
