### ISSUE TITLE
Add creative tag

### ISSUE THREAD

**Issue by ShawnFoxter** [hyperdefined/ToolStats#41]
I'd like to know if it is possible to add a tag to the items taken from creative inventory

**Comment by hyperdefined** [comment]
Maybe, creative menus are mostly client sided, so finding out "this item was spawned via creative" is a bit tricky.

**Comment by hyperdefined** [comment]
This has been added to 1.7.1 https://github.com/hyperdefined/ToolStats/releases/tag/1.7.1
