### ISSUE TITLE
1.7 - Stats applied to crafted bowls

### ISSUE THREAD

**Issue by DormCraft** [hyperdefined/ToolStats#42]
![image](https://github.com/hyperdefined/ToolStats/assets/72905364/76a3b8d0-ff60-4633-bd99-b85eb4b177ab)
Not sure if this is intended, but they won't stack afterwards, I assume due to the data not matching.

**Comment by hyperdefined** [comment]
That is 100% not supposed to happen. Looks like I need to better check if an item is a bow, since "bowl" contains the word bow.

**Comment by hyperdefined** [comment]
I'll release this in the next few days, been working on other things for this update.

**Comment by hyperdefined** [comment]
This has been fixed for 1.7.1 https://github.com/hyperdefined/ToolStats/releases/tag/1.7.1

Thank you for your long term support of the plugin!
