### ISSUE TITLE
Creative item duplicate tags

### ISSUE THREAD

**Issue by DormCraft** [hyperdefined/ToolStats#44]
Creative-item tags are applied to tools not spawned in creative if the player switches gamemodes, and reapplied each time the player enters creative.

![image](https://github.com/hyperdefined/ToolStats/assets/72905364/193210b6-6e94-43b4-bed6-dc22d3f04c4c)

**Comment by hyperdefined** [comment]
I can't seem to replicate this on my end, I'll try to write a fix for this. Do you click on the items at all? Can you provide more detailed steps?

**Comment by DormCraft** [comment]
I believe all that I did was open my inventory in creative, hover the item, and then exit and switch back, but I can do more testing/get a video in the next few days if you can't replicate it.

**Comment by hyperdefined** [comment]
I wrote another check to try and fix this. The creative event fires twice when the item spawns in, so maybe somewhere there it's breaking.

Please try this version. Ignore the exception that pops up about a version not being found.

[toolstats-1.7.1-DEBUG-CREATIVE.zip](https://github.com/hyperdefined/ToolStats/files/13454123/toolstats-1.7.1-DEBUG-CREATIVE.zip)

**Comment by xiantiao233** [comment]
If Chinese is used, it seems that the same problem will arise.

**Comment by hyperdefined** [comment]
Thanks for the report.

I fixed this bug but I did not release an update for it yet. I can do that in a few hours.

**Comment by hyperdefined** [comment]
I thought I did, it looks like I did not fix this.

Can you share me your configuration that uses Chinese? I want to test on my end.

**Comment by hyperdefined** [comment]
Looks like I fixed the issue on my end locally, but never published it. I'll release it shortly.

In theory this should fix all issues with double lore entries.
