### ISSUE TITLE
Incorrect Elytra lore

### ISSUE THREAD

**Issue by Ostro3ve3d** [hyperdefined/ToolStats#5]
If you drop your elytra to another players, your elytra will get one more "Founded by"
https://youtu.be/KAGzBfHOrus

**Comment by hyperdefined** [comment]
Thank you for the bug report, I fixed the issue in version 1.3.2. Please make sure to update!

Also, you can fix the lore by holding the elytra and using `/toolstats reset`. This will remove the duplicated tags.

https://github.com/hyperdefined/ToolStats/releases/tag/1.3.2
