### ISSUE TITLE
Optimalization

### ISSUE THREAD

**Issue by Oskicz** [hyperdefined/ToolStats#53]
Hi so this plugin is awesome its just its usage when there is alot of players Especially when they are mining What i saw on spark (mined block and lore change)

Is there any chance that you could somehow make it use less resources?

**Comment by hyperdefined** [comment]
Could you send a spark report that shows this? I want to see what methods it's calling mostly.

The plugin does update the lore on every single block break. I tried to "narrow" down the checks, so it will only run the lore updating functions when needed. The function itself is a bit complicated, but I didn't expect it to blow up. It's doing some simple find and replace basically.

I myself am not great with optimization, but having a spark report might guide me a little. I haven't really been active with plugin development in a bit, so I'm sorry if this takes a few to get resolved, if I can resolve it.

**Comment by hyperdefined** [comment]
Closing this as it's stale. I don't plan on working on ToolStats right now.
