### ISSUE TITLE
/toolstats reset dnot work

### ISSUE THREAD

**Issue by dol4iua** [hyperdefined/ToolStats#58]
![image](https://github.com/hyperdefined/ToolStats/assets/24779133/74ddaca2-a55c-46f8-857c-14e5d4c0a765)
![image](https://github.com/hyperdefined/ToolStats/assets/24779133/daec5528-d9af-4dd2-85d0-188ba978beac)
![image](https://github.com/hyperdefined/ToolStats/assets/24779133/218193c9-b1f0-4643-9240-ebf861d0c1e3)
I don't know what other information to give you).
There are no errors in the console
purpur-1.20.1-2005

**Comment by dol4iua** [comment]
and pls 
![image](https://github.com/hyperdefined/ToolStats/assets/24779133/bc29e392-6965-4839-8cc5-76ecbf458fb9)
make this massage translatable

**Comment by hyperdefined** [comment]
I'm not sure what the problem is here. When you run the reset command, does the lore not update at all? Can you provide your config?

About translation, I would love to add a messages file to allow translations.

**Comment by dol4iua** [comment]
https://www.youtube.com/watch?v=lWQfXeSWOuE

enabled:
  # Will show ownership of items when they are created/found.
  created-by:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    shears: true
    bow: true
    armor: true
  # Will show time the item is created
  created-date:
    pickaxe: false
    sword: false
    shovel: false
    axe: false
    hoe: false
    shears: false
    bow: false
    armor: false
  # Will show "Fished by <player>"
  fished-tag:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    shears: true
    bow: true
    armor: true
  # Will show "Found by <player>"
  looted-tag:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    shears: true
    bow: true
    armor: true
  # Will show "Trade by <player>"
  traded-tag:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    shears: true
    bow: true
    armor: true
  player-kills:
    sword: true
    axe: true
    trident: true
    bow: true
  mob-kills:
    sword: true
    axe: true
    trident: true
    bow: true
  blocks-mined:
    pickaxe: true
    shovel: true
    axe: true
    hoe: true
    shears: true
  # Will show "Spawned in by <player>"
  spawned-in:
    pickaxe: true
    sword: true
    shovel: true
    axe: true
    hoe: true
    shears: true
    bow: true
    armor: true
  fish-caught: true
  sheep-sheared: true
  armor-damage: true
  dropped-by: true
  elytra-tag: true
  arrows-shot: true

messages:
  created:
    created-by: "&7Створено: &8{player}"
    created-on: "&7Crafted on: &8{date}"
  fished:
    caught-by: "&7Caught by: &8{player}"
    caught-on: "&7Caught on: &8{date}"
    fish-caught: "&7Fish caught: &8{fish}"
  looted:
    looted-by: "&7Добуто: &8{player}"
    looted-on: "&7Looted on: &8{date}"
    found-by: "&7Знайдено: &8{player}"
    found-on: "&7Found on: &8{date}"
  traded:
    traded-by: "&7Обміняно: &8{player}"
    traded-on: "&7Traded on: &8{date}"
  kills:
    mob: "&7Вбито мобів: &8{kills}"
    player: "&7Вбито гравців: &8{kills}"
  spawned-in:
    spawned-by: "&aСтворено: &8{player}"
    spawned-on: "&7Створено: &8{date}"
  blocks-mined: "&7Добуто блоків: &8{blocks}"
  crops-harvested: "&7Культур зібрано: &8{crops}"
  sheep-sheared: "&7Пострижено: &8{sheep}"
  dropped-by: "&7Отримано від: &8{name}" # name will be player/mob name
  damage-taken: "&7Шкоди отрнимано: &8{damage}"
  arrows-shot: "&7Стріл випущено: &8{arrows}"
  # Display this message if the player shift click trades/crafts items. It's not really easy to get every single item
  # that is crafted. The tag will only be added to the first item. If you don't want this message, simply replace them both with ""
  shift-click-warning:
    crafting: "&cCrafting items via shift clicking does not fully apply tags to each item. This is a limitation with the Bukkit API."
    trading: "&cTrading items via shift clicking does not fully apply tags to each item. This is a limitation with the Bukkit API."

# Change the default formatting for dates.
# See: https://www.digitalocean.com/community/tutorials/java-simpledateformat-java-date-format
# Example: "dd/MM/yyyy"
date-format: "M/dd/yyyy"

# Change number formatting.
# You probably do not need to touch this.
number-formats:
  comma-separator: ","
  decimal-separator: "."
  comma-format: "#,###"
  decimal-format: "#,###.00"

# When any tool is created, it will generate a hash for the item.
# This hash is not on the item lore, only stored in the NBT data.
# This has no use currently, but can be used for future features for dupe detection.
generate-hash-for-items: true

config-version: 6

**Comment by dol4iua** [comment]
And where are the statistics stored? if I have 2 servers with shared inventory connected by MySQL Player Data Bridge, will there be no problems?

**Comment by hyperdefined** [comment]
I see the misunderstanding. The reset command is for fixing lore that was lost or broken. It removes all lore, then reapplies the lore based on the stats of the items. It doesn't remove all or reset the statistics.

For where the items are stored, it's stored on the items itself (using NBT). Most likely your plugin for Mysql should sync the playerdata and should be fine.
