### ISSUE TITLE
Wrong behavior with item weared on head

### ISSUE THREAD

**Issue by Ostro3ve3d** [hyperdefined/ToolStats#6]
When you wear item on head with /hat command and take damage, then this item will have "Damage taken" stat
https://www.youtube.com/watch?v=2NWnZbxMLks

**Comment by hyperdefined** [comment]
Completely forgot that `/hat` is a command. I will fix this later today.

**Comment by hyperdefined** [comment]
This issue has been fixed on version 1.3.3!

https://github.com/hyperdefined/ToolStats/releases/tag/1.3.3
