### ISSUE TITLE
Incorrect display of damage on armor

### ISSUE THREAD

**Issue by foxya27** [hyperdefined/ToolStats#64]
![image](https://github.com/hyperdefined/ToolStats/assets/95995512/311401f8-ed21-4365-8823-7bb04c611338)
Version Purpur 1.21, toolstats 1.7.2

**Comment by hyperdefined** [comment]
I've tried to fix this so many times, do you know what you did last before it added this insane damage?

**Comment by foxya27** [comment]
> I've tried to fix this so many times, do you know what you did last before it added this insane damage?

I had the effect of poisoning, I was hit with very high recoil, it was also possible that I was in god mode

**Comment by foxya27** [comment]
> There are some issues with other plugins and damages, I can't really account for them all. Do you possibly know what plugin you were using for god mode?

essentialsx

**Comment by yanshiqwq** [comment]
![图片](https://github.com/user-attachments/assets/d6e3fe44-5d45-442a-a2ea-22f23a3899e1)
[Leaves](https://leavesmc.org/) 1.20.4 / toolstats 1.7.2
same problem

**Comment by hyperdefined** [comment]
Hello, this has been fixed. Please update: https://github.com/hyperdefined/ToolStats/releases/tag/1.7.3
