### ISSUE TITLE
Incorrect display of damage on armor when using vanilla /kill command

### ISSUE THREAD

**Issue by yanshiqwq** [hyperdefined/ToolStats#65]
Reproduce the process: 
1. Obtain a new iron chest armor through `/give @s iron_chestplate`
2. Use vanilla suicide commands `/kill` (essentialsx commands `/suicide` and `/kill` will not reproduce this issue)
3. Result: ![图片](https://github.com/user-attachments/assets/f85c144d-b8b6-455e-a18b-6973b166bf7c)

**Comment by hyperdefined** [comment]
Hello, thank you for the steps in your issue, I fixed this. Please update: https://github.com/hyperdefined/ToolStats/releases/tag/1.7.3
