### ISSUE TITLE
Flight time issue + Armor damage lore not working

### ISSUE THREAD

**Issue by foxya27** [hyperdefined/ToolStats#70]
![image](https://github.com/user-attachments/assets/681e08f6-1452-470e-8a14-1240f23d0b09)
How is it measured in ticks?
I installed it on the server, flew for a minute and saw this number...

**Comment by foxya27** [comment]
I'm sorry that everything is in Russian, but I think you'll understand

**Comment by foxya27** [comment]
![image](https://github.com/user-attachments/assets/aff8edaa-8b38-475d-b66e-a6a525ee385b)
OMG....damage taken attribute it so lagged

**Comment by hyperdefined** [comment]
The flight time is measured in seconds, it's how long you fly for. It starts when you start flying, and when you land it ends. Not sure why it's reporting that insane value.

As for the damage, I didn't see this in my testing, I'll have to try again.

**Comment by foxya27** [comment]
> The flight time is measured in seconds, it's how long you fly for. It starts when you start flying, and when you land it ends. Not sure why it's reporting that insane value.
> 
> As for the damage, I didn't see this in my testing, I'll have to try again.

Another strange thing is that my values ​​do not start from 0, but from like this: “.32”

**Comment by wvbigdave** [comment]
> ![image](https://private-user-images.githubusercontent.com/95995512/365419039-aff8edaa-8b38-475d-b66e-a6a525ee385b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTAwOTEsIm5iZiI6MTcyNTg0OTc5MSwicGF0aCI6Ii85NTk5NTUxMi8zNjU0MTkwMzktYWZmOGVkYWEtOGIzOC00NzVkLWI2NmUtYTZhNTI1ZWUzODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZDdjYmMyOTdhYzJiNGFhZWRlN2I0YzMxNTBhNmVhMDk1YWZhZDFkOGI1ZmJiOWNiNDk5NDY2YmZjYzczYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcVzF4JnXIas2pdwYMR8N5PzYTbjMnanXOwQGmOPVi4) OMG....damage taken attribute it so lagged

I'm getting this exact same issue.  was going to post about it until i seen you already had.

**Comment by hyperdefined** [comment]
I appreciate the reports, I will try my best to fix it.

**Comment by hyperdefined** [comment]
And not even 5 minutes into looking, I found the bug and I fixed it on my end.

**Comment by hyperdefined** [comment]
Please update, new version is here: https://github.com/hyperdefined/ToolStats/releases/tag/1.8.1

**Comment by foxya27** [comment]
> The flight time is measured in seconds, it's how long you fly for. It starts when you start flying, and when you land it ends. Not sure why it's reporting that insane value.

By the way, the flight time is still displayed incorrectly, especially when you fly with fireworks and hit the ground sharply... I simply could not fly 700 blocks in 3 seconds...

**Comment by hyperdefined** [comment]
https://github.com/hyperdefined/ToolStats/releases/tag/1.8.2

The elytra issue has been fixed, please update. I don't have a way to fix the data on the elytra, but running `/toolstats reset confirm` while holding the elytra will fix the duplicate entries.
