### ISSUE TITLE
Hex Colors Issue

### ISSUE THREAD

**Issue by Katables** [hyperdefined/ToolStats#72]
When turning Flight time tracking on, it shows an alarmingly high number that has nothing to do with actual flight time. When editing the config in anyway related to the Flight time, and reloading the plugin it adds a new Flight time with a seemingly doubled number?
Any time the plugin reloads it creates a new flight time with an even higher number.

As you can see from the picture I was adding Hex Support to my Flight time to test it. (Obviously I missed a # lol but you get the point)
![image](https://github.com/user-attachments/assets/0f2a3668-0d64-4b46-b705-99f48af94993)

**Comment by Katables** [comment]
Seems like its doing it with Blocks mined as well 
![image](https://github.com/user-attachments/assets/0873c283-ff73-4538-93ac-b9a84ea96a1a)

**Comment by Katables** [comment]
Even after /toolstats reset confirm 
![image](https://github.com/user-attachments/assets/e95d0fa8-0744-486f-bd0a-18f46ae03aa4)

**Comment by Katables** [comment]
It seems like its the Hex Colors doing it.
Works as intended without the Hex Colors 
![image](https://github.com/user-attachments/assets/2fef4a55-7056-4b3a-a5de-e22c433a4cda)

**Comment by hyperdefined** [comment]
Can you show me your config file? I want to see the hex you are using to test on my end.

**Comment by hyperdefined** [comment]
As for the insanely high flight times, I'm aware of it. I didn't catch it in my testing, will try in a few hours.

**Comment by Katables** [comment]
flight-time: "&#4EC2FCFli&#73CEFBgh&#97D9FAt time: &8{time}"
  ^ This would result in a smooth transition from Blue to light blue.
  
  Taking smooth Gradients from https://coolors.co/4ec2fc-73cefb-97d9fa-aee4ff

**Comment by Katables** [comment]
The Same gradient seen here 
![image](https://github.com/user-attachments/assets/88d36d83-3bb9-4e8f-aa2d-b86c3503fe4f)
![image](https://github.com/user-attachments/assets/09136508-41c0-4b51-b630-0a761ceb367c)

So i know it works as ive used it before. But if thats not how the Hex colors work in your plugin then my bad xD

**Comment by hyperdefined** [comment]
No hex works the exact same, it's the way I update the lore breaking. Mostly the flight time is being calculated incorrectly (see #74).

For the other one (like blocks mined), I will have to test in an hour or so when I am available.

**Comment by Katables** [comment]
Okay no rush :D Thanks for the quick response!

**Comment by hyperdefined** [comment]
This issue has been fixed, please update https://github.com/hyperdefined/ToolStats/releases/tag/1.8.2

I don't have a way to fix the flight times on your elytra, but running the reset command will remove the duplicate entries on any item.
