### ISSUE TITLE
Overwritting Old Data

### ISSUE THREAD

**Issue by Katables** [hyperdefined/ToolStats#73]
Is there any way to overwrite the old data with new data
For example, Non Colorful saved data, being updated with the new Hex Colors.. without creating a new data line.
I dont want to have to reset everyones data.
![image](https://github.com/user-attachments/assets/07364674-e5ee-4f35-93c6-cf7ba5bb76e8)

**Comment by Katables** [comment]
Ah Nvm problem fixed with /toolstats reset confirm. It was creating a new line on the elytra so I didnt think it would work. Sorry should have checked before posting!
![image](https://github.com/user-attachments/assets/f754125a-ab16-43fb-936b-d9af5c176998)

**Comment by hyperdefined** [comment]
It should overwrite the data instead of adding a new line. When it adds a new line, it's failing to parse the old one. I see the bug you reported on the other issue, so I'll go there.
