### ISSUE TITLE
Trident duplicate lore

### ISSUE THREAD

**Issue by DustySpirit** [hyperdefined/ToolStats#75]
When using a trident, killing an entity with the normal left click attack vs the thrown attack outputs different trackers. Along with alternating between each kill action continues to duplicate the lore.

I'm running on an unmodified config of version 1.8.1
here is a screenshot of what it looks like, it goes melee kill, thrown kill, melee kill, thrown kill
![Screenshot_82](https://github.com/user-attachments/assets/ce597745-06c1-4c6c-ac3d-02bb76d1c54b)

**Comment by hyperdefined** [comment]
Hey, please update to 1.8.2, I added the fix onto this version.

https://github.com/hyperdefined/ToolStats/releases/tag/1.8.2

After you update, you can run `/toolstats reset confirm` while holding the trident to fix it.

**Comment by DustySpirit** [comment]
okay, thank you much! this plugin is amazing! is there going to be support for shields?

**Comment by hyperdefined** [comment]
I could, I haven't thought about shields.

**Comment by DustySpirit** [comment]
oo that would be great!
