### ISSUE TITLE
[BUG] Information duplication

### ISSUE THREAD

**Issue by WaxenSs** [hyperdefined/ToolStats#79]
A player on my server has come up with a little technique for duplicating the "Dropped for" information: he drops the item to a zombie, then kills it, then gives the item back to another mob, then kills it again, etc. His item therefore has several "Dropped for" items.

**Comment by WaxenSs** [comment]
No problem:
`minecraft:netherite_sword[custom_model_data=1450001,attribute_modifiers={modifiers: [{amount: -0.1687660962343216d, id: "minecraft:d", operation: "add_multiplied_base", slot: "mainhand", type: "minecraft:generic.movement_speed"}, {amount: -2.4000000953674316d, id: "minecraft:d", operation: "add_value", slot: "mainhand", type: "minecraft:generic.attack_speed"}, {amount: 13.0d, id: "minecraft:d", operation: "add_value", slot: "mainhand", type: "minecraft:generic.attack_damage"}]},custom_name='{"color":"#330099","fallback":"Warping Witherblade","italic":false,"translate":"incendium.item.warping_witherblade.name"}',custom_data={PublicBukkitValues: {"toolstats:origin": 1}, incendium: {item: "warping_witherblade"}},damage=3,lore=['{"extra":[{"bold":false,"color":"#006666","italic":true,"obfuscated":false,"strikethrough":false,"text":"\\"","underlined":false},{"bold":false,"color":"#006666","italic":true,"obfuscated":false,"strikethrough":false,"text":"For in life all things return","underlined":false}],"text":""}', '{"extra":[{"bold":false,"color":"#006666","italic":true,"obfuscated":false,"strikethrough":false,"text":"to death, and in death all things","underlined":false}],"text":""}', '{"extra":[{"bold":false,"color":"#006666","italic":true,"obfuscated":false,"strikethrough":false,"text":"return to the shadow of","underlined":false},{"bold":false,"italic":false,"obfuscated":false,"strikethrough":false,"text":" ","underlined":false},{"bold":false,"color":"#006666","italic":true,"obfuscated":true,"strikethrough":false,"text":"CENSOR","underlined":false},{"bold":false,"color":"#006666","italic":true,"obfuscated":false,"strikethrough":false,"text":"\\"","underlined":false}],"text":""}', '""', '{"extra":[{"bold":false,"color":"#333333","italic":true,"obfuscated":false,"strikethrough":false,"text":"Patron Item","underlined":false}],"text":""}', '""', '{"extra":[{"bold":false,"color":"#FF8000","italic":true,"obfuscated":false,"strikethrough":false,"text":"Incendium","underlined":false}],"text":""}', '{"extra":[{"bold":false,"color":"gray","italic":false,"obfuscated":false,"strikethrough":false,"text":"Lâché par: ","underlined":false},{"color":"dark_gray","italic":false,"text":"Wither"}],"text":""}', '{"extra":[{"bold":false,"color":"gray","italic":false,"obfuscated":false,"strikethrough":false,"text":"Lâché par: ","underlined":false},{"color":"dark_gray","italic":false,"text":"Wither Skeleton"}],"text":""}', '{"extra":[{"bold":false,"color":"gray","italic":false,"obfuscated":false,"strikethrough":false,"text":"Lâché par: ","underlined":false},{"color":"dark_gray","italic":false,"text":"Zombified Piglin"}],"text":""}', '{"extra":[{"bold":false,"color":"gray","italic":false,"obfuscated":false,"strikethrough":false,"text":"Lâché par: ","underlined":false},{"color":"dark_gray","italic":false,"text":"Piglin"}],"text":""}']]`

**Comment by hyperdefined** [comment]
Even more strange, there is not "time created' data, which is what the plugin uses to determine if the item was already dropped or not. This is pretty outdated, as this was done before origin was added.

I'll look into this later today.

**Comment by hyperdefined** [comment]
This feature has been added, please update: https://github.com/hyperdefined/ToolStats/releases/tag/1.8.3
