### ISSUE TITLE
Sword mob kills issue

### ISSUE THREAD

**Issue by kushuser** [hyperdefined/ToolStats#83]
sword, axe, trident kills counting 2-3 mobs when killing a mob instead of 1 kill.

**Comment by kushuser** [comment]
also there too configs in latest version

**Comment by hyperdefined** [comment]
I've never run into multiple kills being counted, I would have to test it. Probably some plugin compatibility.

For two configs, it makes a copy when it upgrades the config to a new version. It still uses the `config.yml` file. The other config file is a backup of the previous one. It states this in the console when it upgrades.

**Comment by hyperdefined** [comment]
Closing this from inactivity.
