### ISSUE TITLE
Add information manually

### ISSUE THREAD

**Issue by WaxenSs** [hyperdefined/ToolStats#86]
Enable certain information to be added manually via a command (e.g. `/toolstats edit created-by [NAME]`). This can be useful when an item is buggy or [missing information](https://github.com/hyperdefined/ToolStats/issues/85). This way, the player can keep his statistics and have his tool free of false or missing information.

**Comment by hyperdefined** [comment]
This has been on the to do list for a while.

**Comment by hyperdefined** [comment]
#76
